# SPDX-License-Identifier: MIT
# Copyright (C) 2025 Max Bachmann
# This file is generated by tools/generate_python.py
from __future__ import annotations

import contextlib
import os

from rapidfuzz._feature_detector import AVX2, SSE2, supports

__all__ = ["default_process"]

_impl = os.environ.get("RAPIDFUZZ_IMPLEMENTATION")
if _impl == "cpp":
    _imported = False
    if supports(AVX2):
        with contextlib.suppress(ImportError):
            from rapidfuzz.utils_cpp_avx2 import (
                default_process,  # pyright: ignore[reportMissingImports]
            )

            _imported = True

    if not _imported and supports(SSE2):
        with contextlib.suppress(ImportError):
            from rapidfuzz.utils_cpp_sse2 import (
                default_process,  # pyright: ignore[reportMissingImports]
            )

            _imported = True

    if not _imported:
        from rapidfuzz.utils_cpp import (
            default_process,  # pyright: ignore[reportMissingImports]
        )
elif _impl == "python":
    from rapidfuzz.utils_py import default_process
else:
    _imported = False
    if supports(AVX2):
        with contextlib.suppress(ImportError):
            from rapidfuzz.utils_cpp_avx2 import (
                default_process,  # pyright: ignore[reportMissingImports]
            )

            _imported = True

    if not _imported and supports(SSE2):
        with contextlib.suppress(ImportError):
            from rapidfuzz.utils_cpp_sse2 import (
                default_process,  # pyright: ignore[reportMissingImports]
            )

            _imported = True

    if not _imported:
        with contextlib.suppress(ImportError):
            from rapidfuzz.utils_cpp import (
                default_process,  # pyright: ignore[reportMissingImports]
            )

            _imported = True

    if not _imported:
        from rapidfuzz.utils_py import default_process
